### PR TITLE
the proxy src should include the hostURL

### PR DESCRIPTION
**Pull request by shrektan**

### CODE REVIEW

**Comment by shrektan** [comment]
Moreover, I think it should be mentioned in the documentation that CORS policy will block the proxy launch by default, if the web's host is not the same as shinyproxy...

**Comment by innesbre** [comment]
Hi @shrektan, how do you get around that CORS policy?  I can't get this demo code to work (even with your fix) and it seems the authors have abandoned it, given the lack of responses to other questions about this in here and on the openanalytics support website.

**Comment by shrektan** [comment]
@innesbre Sorry, it has been some time and I can't recall it. 

I now use docker-compose to host the shinyproxy in production and it looks fine.

**Comment by innesbre** [comment]
> @innesbre Sorry, it has been some time and I can't recall it.
> 
> I now use docker-compose to host the shinyproxy in production and it looks fine.

Thanks, I'm going to take a gander at your demo repo employing that method.

**Comment by willdrew** [comment]
Good afternoon @bioinfomagician, thanks again for your patience. I have reviewed the `README.md` and put some thought into the direction to go; have also begun reviewing the code and have some feedback, but will follow-up with a code review later.

First, thank you for all of your hard work with this ... overall, it's a great first pass of a prototype designed to run on Popper Cluster, especially when considering the on-premise design with its legacy architecture, internal security state and limitations.

Even for the current Popper-AWS ask, it's still a good first pass, but will need some iteration (as you mentioned yourself in the readme) ... from an architecture, security and best practices point of views, we should strive to close up some (as much as possible) of the important security concerns (unfortunately, I don't see us closing them all, while we still use shared resources, at least no until we can move towards using PoLP, decoupling components for proper isolation and separation of concerns).

Therefore, we have our work cut out for us, in order to have Popper-AWS properly utilizing cloud native resources with all important security concerns closed and using best practices, which something we will need to obtain to be compliant as we are now a public company ... too many details to effectively communicate over a PR and further discussion is required anyway.

Further, we should consider revisiting the DevTest environment for the cloud infra (for the Popper Cluster, it's a moot point) as it opens up a lot of security concerns.  Instead, it would be better for us to refactor the images (all the base images) to remove any unencrypted secrets stored at rest for dev, staging and production environments (or at least dev and production), obviously in addition to removing all secrets from the Dockerfile/code/assets/etc in GitHub.  That way, for dev work, one could use the shared Popper-AWS compute resources, the base images (without access to decrypt production secrets during runtime), so Immuneers with elevated system privileges are able to test non-infra concerns using simple auth, etc. w/o us having architecture that compromises security.


That said, I'll provide a list of some of the more pressing security concerns, which apply not only to the image you are developing, but really all of our base images and downstream images --

Therefore, this feedback is not reflection on your work at all (again, great job on the first pass), but about the inadequate state of our current legacy docker images (with secrets in them and github), bare metal infra, etc against where we need to be (or at least get to) in the cloud.


# Secrets/Certs
- In GitHub repo code (should be sanitized / removed completely)
- In ECR images
  - Should be encrypted at rest
  - Should be decrypted during container runtime
  - Something I have done many times before for hardened security and flexibility
    - Loka is looking into this per my request


# Environments
- Test environment (unit tests); can be run as part of the build process and must pass to push a new image to ECR
- Dev environment using base images that don't have access to production secrets/certs
  - Immuneers can use fake/generated account in the config to login, etc
- Staging environment used to test release a new version of an app or services off production infra using production secrets/certs
  - The release should be done programmatically to dedicated resources, ideally using IaC, not direct access to resources to remove security concerns
  - For example, these containers should not be run on any shared resources; otherwise it defeats to purpose as a bad actor could capture login details shared or HTTP, etc


# Docker
- Docker running as rootless (and how that affects ShinyProxy vs regular Immuneer access)
  - Granted, root could still run docker (not best practice, a docker user with any required permissions would be better)
- Docker container access to the docker socket (not necessarily a concern, if deployed an isolated cloud resource)
- Docker container having privileged access (not necessarily a concern, if deployed an isolated cloud resource)
- Security profiles like AppArmor or Seccomp to add to docker and lock it down, especially on shared resources:
  - https://docs.docker.com/engine/security/apparmor/
  - https://docs.docker.com/engine/security/seccomp/


# ShinyProxy
- Ideally running in an HA mode (best practice for production and looks pretty straightforward)
  - In order to achieve this, it seems we'll need an AWS ElastiCache Redis resource
- Running on dedicated cloud resources like ECS EC2/Fargate or likely best AWS EKS (Kubernetes)
  - https://support.openanalytics.eu/t/shinyproxy-in-aws-eks/1043 
- Accessing ShinyProxy and any launched apps via AWS ALB (application load balancer) for TLS support during transit (primary concern) and any HA concerns (secondary concern)
  - Immuneering accessing any app via HTTP is insecure and username/password of one's MS 365 password could be captured by a bad actor
  - Any app itself, of course can run on HTTP, but only if access is fully locked down and restricted to just the HTTPS reverse proxy

# Management of ShinyProxy Apps
- Who has access to launch/start and terminate/stop containers
- How will management be handled
- Related security implications 

# AWS ALB (via ACM, r53, Client VPN)
- Allowing for resolving DNS names that use HTTPS for encryption during transit (and HA, if we want)

# AWS IAM
- Remove most Immuneers from AdministratorAccess
- Created new privileged group giving any required access w/o the keys to the AWS account kingdom
  - PoLP and generally reduces risk (accidental, system compromise, etc)
  - Reduces risk of a lot of notable cycle work during any offboarding


And the list continues, but the above are a few discussion points.  We won't obtain proper and best practice security for some time, but it's something we need to continue iterating on until we get there.  For better or for worse, we have been able to save a lot of money by getting away with very weak internal security (and have been lucky), but that's not something we can continue doing being a public company.

Case in point, pen test (penetration testing) is on the roadmap and until the above (and more) is implemented, we are going to fail.

That all said, these topics above should be kept in mind with the direction going forward and next steps.  Obviously, we're not going to be able to tackle all of this at once, but we should make reasonable efforts to shore things up and iterate.  I know some of this is beyond what you were probably looking for with feedback, but again, it doesn't just apply to your work and something we need to discuss.

For more immediate feedback with the path forward, the next items on the list are likely most important:
# Tackling secrets/creds in GitHub/ECR and ideally decrypting during runtime
  - Allows multipurpose dev/test images and one to change secrets quickly
  - Loka is looking into this

# Tackling AWS ALB (via ACM, r53, Client VPN)
- Allowing for resolving DNS names that use HTTPS for encryption during transit (and HA, if we want)
- I have been iterating on these resources and making good progress; have some prototypes going

# Tackling Docker rootless
- Plugs a major security concerns going forward
- Removes/reduces LDAPS user/group requirement from most base images, if possible (as it will just use your user's access on the host OS)
  -  Another item, I plan to tackle soon (as I've made decent progress on the AMI from Mission)

# ShinyApp (and managed apps)
  - Possible use of Redis to allow HA
  - Possible use in AWS EKS or ECS for PoLP
  - Who and how management of ShinyProxy apps will be handled (and related security implications)
  - Ideally running any production app (managed by ShinyProxy or not) has its own dedicated resource, especially if the docker image uses LDAPS
    - Mentioned for in the Loka SOW the lab folks app, but really any production app really needs to be done this way 

If you login to the Popper-AWS VPN, I know also have a prototype to AWS ALB using AWS ACM and r53 to give us an HTTPS connection a RStudio app: https://rstudio.onc.popper.imrx.tech/auth-sign-in

For dev/testing apps using RStudio under just your account, especially when running docker rootless, one doesn't even necessarily need to login to their RStudio app when using more cloud native solutions (possibly even on shared computes, although some security concerns remain on shared resources).

We are not there yet, but for instance, we could map certain AWS ALBalancers to specific cloud resources  (certain popper-computes) using pre-defined user ports, so Immuneers would have IAM policies that would only allow them access to their apps on a specified servers/ports.  This would work, if we disabled port forwarding and prevented vpn access to ports on EC2 servers (aside from non-admin ssm/terminal access); required access to apps to go through predefined ALBalancers, which Immuneers would securely access via the AWS Client VPN.

I am happy to discuss any of these topics further over a Slack huddle.

That all said, again great job on the first pass!

**Comment by LEDfan** [comment]
Hi

Thank you for opening this PR! The example mentioned in this PR was removed, because there are now better ways to embed a ShinyProxy app, see: https://github.com/openanalytics/shinyproxy-config-examples/tree/master/08-embedded-app

Therefore, I'm going to close this PR, but many thanks for the effort!

**Pull request closed without merging**
